### ISSUE TITLE
No header label on Status Panel, MiniMap or MapControl

### ISSUE THREAD

**Issue by reubene** [axx0/Civ2-clone#65]

**Comment by axx0** [comment]
I added a bold font for headers since I think that's how we used it Eto. It's difficult to compare it with the original civ2 text since raylib makes the characters [smudgy/blurry](https://github.com/raysan5/raylib/issues/2355) .

There are some bugs with the minimap, I'll try to fix that in the coming days.

**Comment by reubene** [comment]
Looks like we need to do some experiments with loading the fonts bigger and drawing smaller. Sounds like you're making some progress though

**Comment by reubene** [comment]
Looks good to me
