### ISSUE TITLE
Dialog not closed

### ISSUE THREAD

**Issue by axx0** [axx0/Civ2-clone#81]
I was doing some testing and disabled drawing of base view in MapControl.cs (line `Raylib.DrawTexture(_currentView.BaseImage, paddedXLoc, paddedYLoc, Color.WHITE)`).
The dialog appears in the background but probably shoudn't:

![Clipboard02](https://github.com/axx0/Civ2-clone/assets/21365802/71703c33-57f2-41a5-b339-9676455ec132)

**Comment by reubene** [comment]
From what I know of raylib if you don't draw on a part of the screen in any draw cycle it leaves visible what was present in the last, so since you're not drawing the map in this screenshot it's showing the last screen from the main menu, it's not redrawing it it's just stale data.  The GameScreen doesn't draw a background image

**Comment by axx0** [comment]
ok, that makes sense
